# *******************************************************************************
# Copyright (c) 2025 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Apache License Version 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0
#
# SPDX-License-Identifier: Apache-2.0
# *******************************************************************************

name: release verification for scrample
on:
  push:
    tags:
      - 'v*'
      - 'release-*'

permissions:
  contents: write

jobs:
  cpp-host-build:
    uses: eclipse-score/cicd-workflows/.github/workflows/tests.yml@c1c90b1a82a1fab0fc202979dde6686b2162d5a8 # v0.0.0
    permissions:
      contents: read
      pull-requests: read
    with:
      bazel-target: "build --config=host //src_cpp:scrample_cpp"

  cpp-qnx-build:
    uses: eclipse-score/cicd-workflows/.github/workflows/qnx-build.yml@c1c90b1a82a1fab0fc202979dde6686b2162d5a8 # v0.0.0
    permissions:
      contents: read
      pull-requests: read
    with:
      bazel-target: "//src_cpp:scrample_cpp"
      bazel-config: "x86_64-qnx"
      credential-helper: ".github/tools/qnx_credential_helper.py"
      environment-name: "workflow-approval"
    secrets:
      score-qnx-license: ${{ secrets.SCORE_QNX_LICENSE }}
      score-qnx-user: ${{ secrets.SCORE_QNX_USER }}
      score-qnx-password: ${{ secrets.SCORE_QNX_PASSWORD }}

  rust-host-build:
    uses: eclipse-score/cicd-workflows/.github/workflows/tests.yml@c1c90b1a82a1fab0fc202979dde6686b2162d5a8 # v0.0.0
    permissions:
      contents: read
      pull-requests: read
    with:
      bazel-target: "build --config=host //src_rust:scrample_rust"

  rust-qnx-build:
    uses: eclipse-score/cicd-workflows/.github/workflows/qnx-build.yml@c1c90b1a82a1fab0fc202979dde6686b2162d5a8 # v0.0.0
    permissions:
      contents: read
      pull-requests: read
    with:
      bazel-target: "//src_rust:scrample_rust"
      bazel-config: "x86_64-qnx"
      credential-helper: ".github/tools/qnx_credential_helper.py"
      environment-name: "workflow-approval"
    secrets:
      score-qnx-license: ${{ secrets.SCORE_QNX_LICENSE }}
      score-qnx-user: ${{ secrets.SCORE_QNX_USER }}
      score-qnx-password: ${{ secrets.SCORE_QNX_PASSWORD }}

  release_verification:
    runs-on: ubuntu-latest
    needs: [cpp-host-build, cpp-qnx-build, rust-host-build, rust-qnx-build]
    if: always() && contains(needs.*.result, 'failure')
    steps:
      - name: Remove release and tag (if exists)
        uses: nikhilbadyal/ghaction-rm-releases@v0.7.0
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RELEASE_PATTERN: ${{ github.ref_name }}
